name: CI

on: [push]

jobs:
  build:
    runs-on: [macOS-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '8.12'
    - name: Install xvfb
      if: matrix.os == 'ubuntu-latest'
      run: apt-get install xvfb firefox
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run vscode:prepublish
    - name: Check
      run: |
        npm run lint
        npm test --silent
